from django.conf.urls import url,include
from .views import (test_perm,index,
                    create_admin_user,web_login,web_logout,
                    parse_the_excel,user_detail,
                    adminer_home,adminer_detail,
                    money_home,book_home,
                    book_home_change_page,
                    book_search,book_detail,
                    add_single_book,user_home,
                    file_download,add_book_excel,plant_home,add_picture,
                    send_message,backmsg,back_wechat,
                    picture_delete)
from android_views import (AndroidUserLoginAPIView,
                           is_login_view,
                           BorrowRecordView,ReturnRecordView,OrderRecordView,
                           AccountsInfoView,RecordSumView,SignItView,InfoView)
urlpatterns = [
    # urls for android admin
    url(r'^android_login/$',AndroidUserLoginAPIView.as_view()),
    url(r'^is_login/$',is_login_view),
    url(r'^record/borrow/$',BorrowRecordView.as_view()),
    url(r'^record/return/$',ReturnRecordView.as_view()),
    url(r'^record/order/$',OrderRecordView.as_view()),
    url(r'^sign/$',SignItView.as_view()),
    url(r'^info/$',InfoView.as_view()),
    # urls for web admin
    url(r'^test/$',test_perm),
    url(r'^index/$', adminer_home,name='newadmin_index'),
    url(r'^create_admin', create_admin_user,name='create_admin_user'),
    url(r'^login/$',web_login,name='web_login'),
    url(r'^logout/$',web_logout,name='web_logout'),
    url(r'^read_file/$',parse_the_excel),
    url(r'^wechat_user/$', user_detail),
    url(r'^adminer_home', adminer_home,name='adminer_home'),
    url(r'^adminer_detail/(?P<user_id>\d+)$',adminer_detail,name='adminer_detail'),
    url(r'^money_home/$', money_home,name='money_home'),
    url(r'^book_home/change_page/1$', book_home,name='book_home'),
    url(r'^book_home/change_page/(?P<back_page>\d+)$',book_home_change_page,name="change_page"),
    url(r'^book_search/$', book_search, name='book_search'),
    url(r'^book_detail/(?P<isbn13>\d+)$$', book_detail, name='book_detail'),
    url(r'^add_book/$',add_single_book,name='add_book'),
    url(r'^add_book_by_excel',add_book_excel,name="add_book_by_excel"),
    url(r'^user_home/$',user_home,name='user_home'),
    url(r'^download/$',file_download,name='download'),
    url(r'^user_detail/(?P<id>\d+)$',user_detail,name='user_detail'),
    url(r'^create_admin/$', create_admin_user,name='create_admin'),
    url(r'^plant_home/$', plant_home,name='plant_home'),
    url(r'^message/$', send_message,name='send_message'),
    url(r'^backmsg/$', backmsg, name='backmsg'),
    url(r'^backwechat/$', back_wechat, name='back_wechat'),
    url(r'^picture_delete/(?P<id>\d+)$',picture_delete,name='picture_delete'),
    url(r'^add_picture/$',add_picture,name='add_picture'),
    # feedback
    # make list
    # url
    # url(r'^delete_picture/(?P<id>\d+)$',delete_picture,'delete_picture'),
]